### ISSUE TITLE
Please Uptate to "es_extended v1-final"

### ISSUE THREAD

**Issue by rcv11x** [iTzCrutchie/esx_moneywash#5]
Hello, could you make this script compatible with the version of es_extended v1-final? thank you very much, now with v1-final this script doesn't work

**Comment by iTzCrutchie** [comment]
Not sure what you mean but the calls are all basically the same if it doesn't work submit errors. I also no longer have an esx server so if it isn't working with the version you specified then submit a PR.

Also include a link to the actual version you are talking about as this was built before they moved to v2 so v1 should work with no issues.

**Comment by rcv11x** [comment]
I have downloaded this script and when I go to the point nothing appears, no point or any option

**Comment by iTzCrutchie** [comment]
Read the instructions. You need to set your own tps AND the spots are by job. Instructions in the  onfig file. If you want anyone to use it srt the job to 'any'
