### ISSUE TITLE
attempt to index a nil vaule (field 'Size')

### ISSUE THREAD

**Issue by MateoCodeScripts** [iTzCrutchie/esx_moneywash#7]
SCRIPT ERROR: @esx_moneywash/client/main.lua:137 attempt to index a nil vaule (field 'Size'), please help me

**Comment by MateoCodeScripts** [comment]
@iTzCrutchie

**Comment by iTzCrutchie** [comment]
Did you edit the config if so make sure you didn't leave a , out anywhere.

**Comment by iTzCrutchie** [comment]
No response for 10 days. I tested on my end and everything is working fine.
